bismillah

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,22 +32,25 @@ jobs:
       run: |
         pip install mlflow==2.14.1 dagshub pandas scikit-learn matplotlib seaborn virtualenv
 
-    # 4. Run MLflow Project ]
-    - name: Run mlflow project
+    # 4 & 5  Jalankan MLflow dan Tangkap ID dari Log
+    - name: Run MLflow & Capture ID
+      id: get_run  
       run: |
         cd Workflow-CI/MLProject
         
-        mlflow run . --env-manager=local --experiment-name "Eksperimen_RF_Automated"
-
-    # 5. Get Latest Run ID 
-    - name: Get latest MLflow run_id
-      id: get_run
-      run: |
+        mlflow run . --env-manager=local --experiment-name "Eksperimen_RF_Automated" > output.log 2>&1
         
-     
-        RUN_ID=$(cat MLProject/last_run_id.txt)
-        echo "Detected Run ID: $RUN_ID"
+      
+        cat output.log
+        RUN_ID=$(grep "Run ID saved:" output.log | awk '{print $NF}')
         
+        
+        if [ -z "$RUN_ID" ]; then
+          echo "ERROR: Tidak bisa menemukan Run ID. Pastikan modelling.py sudah diperbarui."
+          exit 1
+        fi
+        
+        echo "SUKSES! Run ID ditemukan: $RUN_ID"
         
         echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
 
